/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  rober
 * Created: 23-mag-2016
 */

CREATE TABLE goccia (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(256),
    cognome VARCHAR(256),
    username VARCHAR(256),
    password VARCHAR(256),
    saldo DOUBLE PRECISION
);

CREATE TABLE venditore (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gocciaId INTEGER,
    FOREIGN KEY (gocciaId) REFERENCES goccia(id)
);

CREATE TABLE cliente (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gocciaId INTEGER,
    FOREIGN KEY (gocciaId) REFERENCES goccia(id)
);

CREATE TABLE prodotto (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(256),
    urlImmagine VARCHAR(256),
    descrizione VARCHAR(512),
    prezzo DOUBLE PRECISION,
    gocciaId INTEGER,
    FOREIGN KEY (gocciaId) REFERENCES goccia(id)
);